/*
 * generated by Xtext 2.21.0
 */
package com.systemassembly.sm.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmDslUiModule extends AbstractSmDslUiModule {

	public SmDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
