/*
 * generated by Xtext 2.21.0
 */
package com.systemassembly.sm.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SmDslWebModule extends AbstractSmDslWebModule {
}
